### ISSUE TITLE
Possible bug in nats-pure.rb/lib/nats/io /client.rb#1828

### ISSUE THREAD

**Issue by dsuarezbspot** [nats-io/nats-pure.rb#137]
### What version were you using?

2.3.0

### What environment was the server running in?

Using the managed NATS offering, through `tls://connect.ngs.global`

### Is this defect reproducible?

conn = ::NATS.connect('tls://connect.ngs.global', {:servers=>['tls://connect.ngs.global'], :reconnect_time_wait=>30.0, :max_reconnect_attempts=>1, :user_credentials=><Filepath_to_creds>})

According to the documented source code [here](https://github.com/nats-io/nats-pure.rb/blob/v2.3.0/lib/nats/io/client.rb#L40), the first arg above should be a string (which I am providing in this example).

When the execution flow ultimately ends up [here](https://github.com/nats-io/nats-pure.rb/blob/v2.3.0/lib/nats/io/client.rb#L1828), the call to `uri.scheme.to_sym` fails, because `uri` is a String, and does not have a `.scheme` method.

However, 4 lines above this ([here](https://github.com/nats-io/nats-pure.rb/blob/v2.3.0/lib/nats/io/client.rb#L1824)), the `uri` is turned into a `uri_object`.

### Given the capability you are leveraging, describe your expectation?

I would expect to be able to establish a connection to the server using the `tls://connect.ngs.global` server uri.

### Given the expectation, what is the defect you are observing?

I believe the call [here](https://github.com/nats-io/nats-pure.rb/blob/v2.3.0/lib/nats/io/client.rb#L1828) should be `uri_object.scheme.to_sym`, rather than what it is (`uri.scheme.to_sym`).

**Comment by wallyqs** [comment]
Fixed via #135

**Comment by dsuarezbspot** [comment]
Thanks for the follow up @wallyqs !
