### ISSUE TITLE
JSON parse error on processing INFO if we have whitespace in NATS server version

### ISSUE THREAD

**Issue by videlov** [nats-io/nats-pure.rb#38]
We face a JSON parse error when we are using BOSH forked NATS 1.3.0 server from:
https://github.com/bosh-dep-forks/gnatsd

our build script
https://github.com/bosh-dep-forks/gnatsd/blob/d6d6c1935a05a913fa03f6d7bc63db8371b2588d/ci/tasks/build.sh#L19-L23

is setting the server version to: "1.3.0 <time_stamp> <git_rev>"
which breaks the INFO parsing in:
https://github.com/nats-io/nats-pure.rb/blob/7f78ee2a86c56cdff369a6e5365c7516a0b60d30/lib/nats/io/client.rb#L984-L985

because we have a whitespace in the JSON with the server version.
We solved it with a something like that:
https://github.com/videlov/nats-pure.rb/commit/651ee18b74446248ce4a3de22d1fbd9c01076a7b

Would you please fix this for our custom NATS server version?

Thanks in advance.

**Comment by friegger** [comment]
@h4xnoodle @jfmyers9 fyi

**Comment by wallyqs** [comment]
Thanks for the report, I will release minor gem update with the fix later today.

**Comment by wallyqs** [comment]
gem with the fix has been released: https://rubygems.org/gems/nats-pure/versions/0.6.2
