### ISSUE TITLE
Memory leak with request/reply

### ISSUE THREAD

**Issue by jgaskins** [nats-io/nats-pure.rb#47]
I'm seeing ever-increasing memory usage in my Rails app when using NATS request/reply. I was able to reproduce it with this code (the reply is generated in another process to keep this reproduction minimal and avoid ambiguity in where the leak resides):

```ruby
require 'nats/io/client'

nats = NATS::IO::Client.new.tap(&:connect)
1_000_000.times { nats.request("my.subject", "") }
```

I ran it against Ruby 2.6.5, 2.7.2, and 3.0.0. All exhibit the memory leak.

It looks like the client's `@resp_map` ivar is not letting go of the responses after they've been returned or yielded to the `request` block.

**Comment by wallyqs** [comment]
This got fixed in #50 thanks again for the report and apologies for the delay...
