### ISSUE TITLE
require 'nats/client' not working

### ISSUE THREAD

**Issue by storresbaires** [nats-io/nats-pure.rb#62]
hi guys! when you add `nats-pure` to the gem file, by default it adds 0.7.2 version.
When you need to `require 'nats/client'` (as `readme` shows) it says that it cannot find the file. Instead you can import the code with `require 'nats/io/client'`.

**Comment by wallyqs** [comment]
Sorry for the inconvenience, the readme is meant to be for the v2 version of the gem which you can use by setting `2.0.0.pre.rc1` explicitly in the Gemfile as the version.

**Comment by wallyqs** [comment]
Closing since v2.0.0 was released thus fixed.
