### ISSUE TITLE
Slow consumer detection

### ISSUE THREAD

**Issue by blainejohnson17** [nats-io/nats-pure.rb#75]
We're interested in slow consumer detection as described in this [NATS doc page](https://docs.nats.io/using-nats/developer/connecting/events/slow#detect-a-slow-consumer-and-check-for-dropped-messages). 

The doc page indicates that slow consumer check is not available in the ruby client. Is that correct? if so, what are the other options to detect slow consumer?

**Comment by stephen-at-gpn** [comment]
@wallyqs - any suggestions?

**Comment by wallyqs** [comment]
Thanks for pointing out to that page, we need to update that example. By default a subscription would have 65K pending messages limit after which it would become a slow consumer. This can be modified via the `pending_msgs_limit` option `subscribe(pending_msgs_limit: <number>)`:

https://github.com/nats-io/nats-pure.rb/blob/aa8a1ca07d0d3048c656af73b378b8c79ebef3f4/lib/nats/io/client.rb#L426-L436

**Comment by blainejohnson17** [comment]
@wallyqs , thanks for confirming what a slow consumer is. We’re specifically looking for the slow consumer detection callback in the Ruby client (similar to what the go client offers).

**Comment by wallyqs** [comment]
That would be the error callback `nats.on_error`. You can find an example from the specs here: https://github.com/nats-io/nats-pure.rb/blob/main/spec/client_errors_spec.rb#L169-L178

**Comment by blainejohnson17** [comment]
perfect, thank for the help @wallyqs
